# Generated by Django 4.0.4 on 2022-04-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to='minBooks/static/minBooks/images/'),
        ),
    ]
